name: Setup and Restore

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  setup-and-restore:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        run: dotnet build --no-restore
        
  test-tests-class:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test for Tests class
        id: test-tests
        run: |
          dotnet test --no-build --verbosity normal \
            --filter "FullyQualifiedName~UnitTests.Tests"
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

  test-tests2-class:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test for Tests2 class
        id: test-tests2
        run: |
          dotnet test --no-build --verbosity normal \
            --filter "FullyQualifiedName~UnitTests.Tests2"
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results

  notify-github:
    runs-on: ubuntu-latest
    needs: [test-tests-class, test-tests2-class]

    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: test-results

      - name: Summarize test results
        run: echo "Test results summary here"

      - name: Create check runs
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            const testResults = fs.readFileSync('./test-results', 'utf8');
            const testResultsSummary = "Test results summary:\n" + testResults;

            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Test Results",
              head_sha: context.sha,
              status: "completed",
              conclusion: "success",
              output: {
                title: "Test Results",
                summary: testResultsSummary
              }
            });
