name: Setup, Build, and Test

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  unit-tests-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run Unit Tests for Tests class
        run: |
          dotnet test --no-build --verbosity normal \
            --filter "FullyQualifiedName~UnitTests.Tests"

  unit-tests-tests2:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run Unit Tests for Tests2 class
        run: |
          dotnet test --no-build --verbosity normal \
            --filter "FullyQualifiedName~UnitTests.Tests2"