# test_tests.yml
name: Test for Tests Class

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-tests-class:
    needs: setup-and-restore
    runs-on: ubuntu-latest

    steps:
      - name: Test for Tests class
        run: |
          dotnet test --no-build --verbosity normal \
            --filter "FullyQualifiedName~UnitTests.Tests"